from . import idhandlers
from . import regexhandlers
from . import stateshandlers
from . import atherhandlers
from . import kontenthandler
from . import commandsFilrt
from . import hastgahandlers
from . import texthandler
from . import start
from . import help
from . import echo